sudo: false

language: node_js

node_js:
  - "4"
  - "6"

cache:
  directories:
    - node_modules

notifications:
  email: false

install:
  - npm i
  - npm install -g coveralls

script:
  - npm prune
  - npm test

after_script:
  - npm run coverage
  - coveralls < ./coverage/lcov.info || true
